GET http://localhost:3000 HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users?page=2&limit=10 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name":"lemuel de sousa",
    "email": "lemuel@email.com",
    "password": "senha"
}

###
PUT http://localhost:3000/api/users/1 HTTP/1.1
content-type: application/json

{
    "name": "updated name",
    "email": "updated@email.com",
    "password": "newpassword"
}

###
DELETE http://localhost:3000/api/users/1 HTTP/1.1
content-type: application/json
