INSERT INTO users (name, email, password) VALUES
('Alice Johnson', 'alice.johnson@example.com', 'password123'),
('Bob Smith', 'bob.smith@example.com', 'password123'),
('Charlie Brown', 'charlie.brown@example.com', 'password123'),
('Diana Prince', 'diana.prince@example.com', 'password123'),
('Ethan Hunt', 'ethan.hunt@example.com', 'password123'),
('Fiona Gallagher', 'fiona.gallagher@example.com', 'password123'),
('George Michael', 'george.michael@example.com', 'password123'),
('Hannah Montana', 'hannah.montana@example.com', 'password123'),
('Ian Malcolm', 'ian.malcolm@example.com', 'password123'),
('Jane Doe', 'jane.doe@example.com', 'password123'),
('Kevin Hart', 'kevin.hart@example.com', 'password123'),
('Laura Palmer', 'laura.palmer@example.com', 'password123'),
('Michael Scott', 'michael.scott@example.com', 'password123'),
('Nancy Drew', 'nancy.drew@example.com', 'password123'),
('Oscar Wilde', 'oscar.wilde@example.com', 'password123'),
('Pam Beesly', 'pam.beesly@example.com', 'password123'),
('Quentin Tarantino', 'quentin.tarantino@example.com', 'password123');
